project:
  type: website

website:
  title: "Ben Welman"
  favicon: images/logo.png
  site-url: "https://bwelman.github.io/"
  repo-url: "https://github.com/bwelman/bwelman.github.io"
  repo-actions: [issue]
  navbar:
    title: Home
    logo: images/logo-transparant.png
    right:
      - text: Studieboeken
        href: studieboeken.qmd
      - text: Softwijs
        href: softwijs.qmd
      - text: Vlearmoesbier
        href: vlearmoesbier.qmd
  page-footer:
    left:
      - "copyright 2022, Ben Welman"

execute:
  freeze: auto

format:
  html:
    theme: mystyles.scss
    mainfont: "Source Sans Pro"
    toc: true
    link-external-newwindow: true

lang: nl
