project:
  type: website

website:
  title: "Ben Welman"
  favicon: images/logo.png
  navbar:
    title: softwijs
    logo: images/logo-transparant.png
    right:
      - icon: home
        text: Home
        href: index.qmd
      - text: Studieboeken
        href: studieboeken.qmd
      - icon: github
        href: https://github.com/bwelman
  page-footer:
    left:
      - "copyright 2022, Ben Welman"

format:
  html:
    theme: mystyles.scss
    mainfont: "Source Sans Pro"
    toc: true
    link-external-newwindow: true

lang: nl
