project:
  type: website

website:
  title: "Archief Ben"
  description: "Verzameling van documenten over allerlei onderwerpen."
  favicon: images/logo.png
  site-url: "https://bwelman.github.io/"
  repo-url: "https://github.com/bwelman/bwelman.github.io"
  google-analytics: "G-DZG4072LJ3"
  navbar:
    logo: images/logo-transparant.png
    left:
      - text: Home
        href: index.qmd
      - text: Access
        href: access.qmd
      - text: Excel
        href: excel.qmd
      - text: Bier
        href: bier.qmd
      - text: Chemie
        href: chemie.qmd
      - text: R
        href: r.qmd
      - text: Divers
        href: divers.qmd
      - text: Tutorials
        href: tutorials.qmd

  page-footer:
    left: |
      Deze website is gemaakt met <a href="https://quarto.org/">Quarto</a>.
format:
  html:
    theme: include/mystyles.scss
    mainfont: "Source Sans Pro"
    toc: true
    toc-depth: 3
    page-layout: article
    title-block-banner: false
    link-external-newwindow: true
    smooth-scroll: true

execute:
  freeze: auto

lang: nl

editor: visual

